title: Ricardotang's Blog
description: >
  Record My Learning.
baseurl: "/Ricardotang.github.io"
#url: "https://github.com/siawyoung/immaculate"
paginate:	2 # The number of posts to show per page on your homepage
name: "Yichen Hua"
#markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
